### ISSUE TITLE
TestRail._run_by_id does not return correctly

### ISSUE THREAD

**Issue by Cornel-Craveta** [travispavek/testrail-python#121]
The method testrail.client.TestRail#_run_by_id is not returning the result correctly.

It should be:

    @run.register(int)
    @singleresult
    def _run_by_id(self, run_id):
        return filter(lambda p: p.id == run_id, self.runs())

instead of

    @run.register(int)
    @singleresult
    def _run_by_id(self, run_id):
        filter(lambda p: p.id == run_id, self.runs())

**Comment by travispavek** [comment]
Thanks for catching this!
