### ISSUE TITLE
Unable to connect to my instance of TestRail

### ISSUE THREAD

**Issue by UpsetPelican** [travispavek/testrail-python#134]
Followed the instruccions, created my `.conf` file with api key, user and URL got a 401 status response every time when getting projects:

`testrail.helper.TestRailError: {'error': 'Authentication failed: invalid or missing user/password or session cookie.', 'response_headers': "{'Content-Type': 'application/json; charset=utf-8', 'Date': 'Tue, 04 Sep 2018 15:24:02 GMT', 'Server': 'nginx/1.13.12', 'Content-Length': '87', 'Connection': 'keep-alive'}", 'payload': None, 'url': 'https://wizeline.testrail.net/index.php?/api/v2/get_projects', 'status_code': 401}`

Also tried using Environment Variables and password instead of api key with the same result.

Using python 3.6
OS X High Sierra 10.13.6 (17G65)

**Comment by travispavek** [comment]
From an interactive shell run the following to make sure the correct credentials are being picked up.

from testrail import TestRail
client = TestRail()
client.api._auth

**Comment by UpsetPelican** [comment]
Thanks trying it now, letting you know the results

**Comment by UpsetPelican** [comment]
Result: 
`('u****@w***.com', 'mysecretvalidtoken')` 

obfuscated sensitive information but I'm getting the right info

**Comment by travispavek** [comment]
could you outline the calls you are doing to where you reach that error?

**Comment by UpsetPelican** [comment]
I ran the example on the interactive shell skipping the argparse part, then when that failed I downloaded the `end_to_end_example.py`, replaced the projects to match my project ID and ran it as is

**Comment by UpsetPelican** [comment]
After running the last snippet I get the same Auth failed error full trace:

`>>> for p in client.projects():
...     print(p.name)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/testrail/client.py", line 51, in projects
    return ProjectContainer(list(map(Project, self.api.projects())))
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/testrail/api.py", line 237, in projects
    self._projects['value'] = self._get('get_projects')
  File "<decorator-gen-4>", line 2, in _get
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "<decorator-gen-3>", line 2, in _get
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/uriel.coria/Projects/insikt-automation/env-insikt/lib/python3.6/site-packages/testrail/api.py", line 635, in _get
    raise TestRailError(response)
testrail.helper.TestRailError: {'error': 'Authentication failed: invalid or missing user/password or session cookie.', 'response_headers': "{'Content-Type': 'application/json; charset=utf-8', 'Date': 'Wed, 05 Sep 2018 16:16:14 GMT', 'Server': 'nginx/1.13.12', 'Content-Length': '87', 'Connection': 'keep-alive'}", 'payload': None, 'url': 'https://mytestrail.testrail.net/index.php?/api/v2/get_projects', 'status_code': 401}`

**Comment by travispavek** [comment]
Could you try using TestRails library with the same creds. This way we can narrow it down to something with your setup or the module. It looks like you are using TestRails cloud option but just to confirm are you using cloud or on premise?

**Comment by UpsetPelican** [comment]
It is the cloud version, I'll try the TR library and let you know

**Comment by UpsetPelican** [comment]
So here are my findings:
1. Testrail API doesn't seem to like my API key
2. Retried with the password instead of API key - SUCCESS
3. Retried `testrail-python` with the password instead of `TESTRAIL_USER_KEY` and it worked, I was able to get the projects.

Thanks for your time @travispavek, I'll close the issue.

**Comment by x0000ff** [comment]
Just in case if someone still face this problem (e.g. me).

I've found that you have to press **Save Settings** after adding an API keys 🫠

| Not Saved | Saved |
|---|---|
| ![not-saved](https://github.com/travispavek/testrail-python/assets/1062240/a95b2d2b-3871-494c-bcd0-49a89f7c3de8) | ![saved](https://github.com/travispavek/testrail-python/assets/1062240/c8c4ceb1-1650-4991-bdf2-6d000d59ae44) |

**Comment by greg-nance** [comment]
> I've found that you have to press **Save Settings** after adding an API keys 🫠

THANK YOU.
