### ISSUE TITLE
Bug: helper.singleresult calls len on filter objects

### ISSUE THREAD

**Issue by levi-rs** [travispavek/testrail-python#22]
Python 3 functions like `map` and `filter` return iterator objects, not `list` objects like in python 2. The `helper.singleresult` function accepts a generic object, `items`, and calls `len(items)` to check the length. This can fail in python 3, as `items` can often be `filter` or `map` objects with no `__len__` method defined.

**Comment by travispavek** [comment]
This was a big enough bug I pushed version 0.3.1.  

Thanks.
