### ISSUE TITLE
Investigate why API function are not using project_id

### ISSUE THREAD

**Issue by travispavek** [travispavek/testrail-python#4]
I believe project_id is being set during initialization.  Why are we not using it?

**Comment by levi-rs** [comment]
I've noticed this too. Perhaps something to do with the the project_id being stored as a class variable, but referenced/updated by an instance variable?

**Comment by levi-rs** [comment]
Here is at least one reason, wrong key value (`id` instead of `project_id`):
https://github.com/travispavek/testrail-python/blob/fd1fac879100eaeafb73908290d486840cfcead5/testrail/run.py#L94
