### ISSUE TITLE
Question about stability of API

### ISSUE THREAD

**Issue by sleonov** [travispavek/testrail-python#63]
We just installed instance of testrail and considering what API to use
What comes with vendor is bare bones REST API skeleton, and I found yours

Question I have is how stable this API is as of date?
I like how you broke down all the components of TestRail into classes - makes it easier to code

Please let me know, thanks
sleonovich@micron.com

**Comment by levi-rs** [comment]
I can't speak for Travis, but I've been using this package to access the API since March of this year, and have found everything to be very stable. Right now I do roughly 20 to 30 thousand tests a month, in roughly 900 test runs, and no problems.

**Comment by travispavek** [comment]
Hi Sergey,

We do not have 100% API coverage. However I believe that the functionality we do have is fairly solid and I think our test coverage of that functionality is pretty good. I know there are at least a couple individuals who use this client extensively. Hopefully some day we will get to 100% API coverage but right now new functionality primary comes based by needs. I also do not anticipate there being any breaking changes. 

I would suggest you try it out and see if it meets all or most of your needs. PRs are always welcomed!

**Comment by sleonov** [comment]
Thank you all for your replies...Do you have ETA on API documentation being available?
Some basic use cases - get list of projects, list test suites, update test cases, etc

**Comment by travispavek** [comment]
I could add a couple use cases in the README but there are no plans for documentation in the immediate future.  That being said I think the code is very self explanatory and predictable.

**Comment by sleonov** [comment]
thanks
