### ISSUE TITLE
Cache updating of tests after adding/updating results is problematic

### ISSUE THREAD

**Issue by levi-rs** [travispavek/testrail-python#64]
Consider the following scenario:

1.  I have a newly created run, with a single test case associated with that run
2. I get a reference to the test from the run, which creates a Test object and adds the test to the `_tests` cache. At this point the test's status is `Untested`
3. I run through my scenario and decide the test has passed, creating a new Result object, associating it with the Test, and giving it a Status of Passed
4. I use the TR client to add the Result to TestRail

At this point, the Test that exists in the `_tests` cache is now outdated, as it never gets updated with the new status. If I attempt to access the test again before the cache timeout expires, I will get the test as it exists in the cache, with a status of `Untested`.

This is problematic for me as I am moving to concurrent consumer architecture, and I can't rely on cache expirations to get up to date test objects.

**Comment by levi-rs** [comment]
It appears that when you POST a new result through the TestRail API, the response object is the updated test:
http://docs.gurock.com/testrail-api2/reference-results#add_result

Should be able to modify `api.py` to update the `_tests` cache.

**Comment by levi-rs** [comment]
@travispavek there are a couple approaches here, mainly done by modifying the [API's add_result method](https://github.com/travispavek/testrail-python/blob/master/testrail/api.py#L501):

First, you could set all tests associated with that run to refresh by setting the associated `_tests` timestamp to None:
```
    def add_result(self, data):
        fields = ['status_id',
                  'comment',
                  'version',
                  'elapsed',
                  'defects',
                  'assignedto_id']

        payload = self._payload_gen(fields, data)
        self._post('add_result/%s' % data['test_id'], payload)

        # Need to update the _tests cache to refresh on the next query
        for run in self._tests:
            for index, test in enumerate(self._tests[run]['value']):
                if test['id'] == data['test_id']:
                    self._tests[run]['ts'] = None
                    return
        else:
            raise TestRailError("Could not find test '%s' in cache to update" % data['test_id'])
```
The downside to this approach is that runs in `_tests` might be set to refresh so often that the benefits of caching might not be observed.

Second, you could proactively poll the TestRail API for the updated test, and then update the test in the _tests cache:
```
    def add_result(self, data):
        test_id = data['test_id']

        fields = ['status_id',
                  'comment',
                  'version',
                  'elapsed',
                  'defects',
                  'assignedto_id']

        payload = self._payload_gen(fields, data)
        self._post('add_result/%s' % test_id, payload)

        # Need to update the _tests cache with the new test
        updated_test = self.test_with_id(test_id)
        for run in self._tests:
            for index, test in enumerate(self._tests[run]['value']):
                if test['id'] == test_id:
                    self._tests[run]['value'][index] = updated_test
                    return
        else:
            raise TestRailError("Could not find test '%s' in cache to update" % test_id)
```

The potential downside here is that the `_tests` cache might reach its refresh time before the updated test ever gets referenced. If that happens often, or a majority of the time, then we are making unnecessary calls to the TestRail API.

Do you have a preference on which way seems best? Or perhaps a different approach to reach the same end?

**Comment by travispavek** [comment]
I like the idea of just marking it for refresh. I don't suspect there are many times where someone would be adding results and then trying to fetch them right away again. If it does cause a problem it will probably be an immediate and very noticeable one at which point we can further discus a solution.
