### ISSUE TITLE
How to get list of Test Suites for a project

### ISSUE THREAD

**Issue by sleonov** [travispavek/testrail-python#65]
Sorry for a newbie question. I am just getting my feet wet with Test Rail.

I want to get list of Test Suites from a particular project.
I am not sure how to do it right. Is it a method on Project class or API class?
Can someone please give me some examples please.

I have 2 projects - which I can list with API. Project ids are 1 and 2

Thanks

**Comment by levi-rs** [comment]
This works for me:
```
tr = TestRail(11)  # My example project has ID 11
suites = tr.suites()
```

**Comment by sleonov** [comment]
thank you. I was able to pull list of Test Suites
