### ISSUE TITLE
Help on creating/updating test runs

### ISSUE THREAD

**Issue by sleonov** [travispavek/testrail-python#69]
Need help again.
If someone has code examples on how to create a test run from a test case, and update it, please post it.
Thanks much!

**Comment by levi-rs** [comment]
Travis just merged in an end-to-end example I added:
https://github.com/travispavek/testrail-python/blob/master/examples/end_to_end_example.py

I'm planning to make a second example, where you selectively add tests to a run, but that wont happen for a little bit.

**Comment by sleonov** [comment]
Thank you!

**Comment by sleonov** [comment]
Got this error. Where do I link suite id to the run?

    run = tr.add(new_run)
  File "/usr/lib/python3.4/site-packages/testrail/helper.py", line 22, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
  File "/usr/lib/python3.4/site-packages/testrail/client.py", line 222, in _add_run
    return Run(self.api.add_run(obj.raw_data()))
  File "/usr/lib/python3.4/site-packages/testrail/api.py", line 26, in wrapped_f
    api_resp = f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/testrail/api.py", line 424, in add_run
    return self._post('add_run/%s' % project_id, payload)
  File "<string>", line 2, in _post
  File "/usr/lib/python3.4/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/lib/python3.4/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/lib/python3.4/site-packages/testrail/api.py", line 584, in _post
    raise TestRailError(response)
testrail.helper.TestRailError: {'status_code': 400, 'error': 'Field :suite_id is a required field.', 'url': 'http://XXXXXXXXX/testrail//index.php?/api/v2/add_run/2', 'data': {'name': 'Creating a new Run through the API', 'include_all': True}}

**Comment by levi-rs** [comment]
I'm guessing you are working with a project that isn't in single suite mode. From the TestRail API docs about the `suite_id` parameter:
```
The ID of the test suite for the test run (optional if the project is operating in single suite mode, required otherwise)
```

This will require some additions to (at least) `api.py` to support.

**Comment by sleonov** [comment]
just an FYI, I set the project to single suite model, but I am getting the same error

project.suite_mode = 1

**Comment by levi-rs** [comment]
Well, the suite mode is determined on the TestRail side when you create your project:

![screen shot 2016-10-05 at 12 18 58 pm](https://cloud.githubusercontent.com/assets/11619428/19123831/057fca92-8af6-11e6-80e2-3dd5ddc7f1e5.png)

I'm working on a PR to fix this. As a work around, you could manually set the suite_id in the run:
```
new_run._content['suite_id'] = suite.id
```

**Comment by levi-rs** [comment]
@sleonov what that ^^^ PR gets merged, you should be able to set the Suite using
```
new_run.suite = suite
```

**Comment by sleonov** [comment]
suite is suite numeric id, right? Or I need to pass suite object?

**Comment by levi-rs** [comment]
Pass an actual suite object. Keep in mind you will need to reinstall testrail package.
